### ISSUE TITLE
小妹妹你这里怎么可以什么都木有...

### ISSUE THREAD

**Issue by ferstar** [feixiao5566/learnpythonthehardway#1]
## 如题
- 如题

`如题`

> 如题

```
回复请见下条:^>
```

**Comment by feixiao5566** [comment]
because i haven`t learned the course yet. you could see my python practice with liaoxuefeng`s course at:https://github.com/feixiao5566/Py_Rabbic

**Comment by ferstar** [comment]
da shen hao ni hai, wo hu bui ying wen. -(

**Comment by ferstar** [comment]
@feixiao5566 

> グレート神こんにちは厳しい、私はあなたを崇拝します！
